name: Build and Deploy Script
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build-deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Adding Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm ci

      - name: Build Angular App
        run: npm run build

      - name: Deploy to gh pages
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run deploy
